# Lenguajes nativos con mayor cantidad de hablantes
SELECT 
(SUM(?n_speakers) as ?n_speakerss)
?language
WHERE {
  ?continent wdt:P31 wd:Q5107 .
  ?country wdt:P31 wd:Q6256 ;
             rdfs:label ?country_name .
  {?country wdt:P361 wd:Q18} UNION {?country wdt:P361 wd:Q49}
  ?country wdt:P2936 ?language .
  ?country wdt:P1082 ?n_habitantes .
  ?language wdt:P1098 ?n_speakers .
  FILTER(lang(?country_name)='en')
  FILTER(NOT EXISTS {
    {?country_2 wdt:P30 wd:Q46 } UNION {?country_2 wdt:P361 wd:Q458} UNION {?country_2 wdt:P30 wd:Q48} .
     ?country_2 wdt:P2936 ?language .
  })
}
GROUP BY ?language
HAVING(?n_speakerss > 100000)
ORDER BY ?n_speakerss